# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1090, 747)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(80, 20))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_losuj = QtWidgets.QWidget()
        self.tab_losuj.setObjectName("tab_losuj")
        self.label_cytat = QtWidgets.QLabel(self.tab_losuj)
        self.label_cytat.setGeometry(QtCore.QRect(50, 50, 941, 331))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setItalic(False)
        self.label_cytat.setFont(font)
        self.label_cytat.setAutoFillBackground(False)
        self.label_cytat.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.label_cytat.setWordWrap(True)
        self.label_cytat.setObjectName("label_cytat")
        self.label_autor = QtWidgets.QLabel(self.tab_losuj)
        self.label_autor.setGeometry(QtCore.QRect(370, 450, 611, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setItalic(True)
        self.label_autor.setFont(font)
        self.label_autor.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_autor.setWordWrap(True)
        self.label_autor.setObjectName("label_autor")
        self.button_previous = QtWidgets.QPushButton(self.tab_losuj)
        self.button_previous.setGeometry(QtCore.QRect(150, 520, 200, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_previous.sizePolicy().hasHeightForWidth())
        self.button_previous.setSizePolicy(sizePolicy)
        self.button_previous.setMinimumSize(QtCore.QSize(80, 20))
        self.button_previous.setObjectName("button_previous")
        self.button_random = QtWidgets.QPushButton(self.tab_losuj)
        self.button_random.setGeometry(QtCore.QRect(360, 520, 200, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_random.sizePolicy().hasHeightForWidth())
        self.button_random.setSizePolicy(sizePolicy)
        self.button_random.setMinimumSize(QtCore.QSize(80, 20))
        self.button_random.setObjectName("button_random")
        self.button_next = QtWidgets.QPushButton(self.tab_losuj)
        self.button_next.setGeometry(QtCore.QRect(580, 520, 200, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_next.sizePolicy().hasHeightForWidth())
        self.button_next.setSizePolicy(sizePolicy)
        self.button_next.setMinimumSize(QtCore.QSize(80, 20))
        self.button_next.setObjectName("button_next")
        self.tabWidget.addTab(self.tab_losuj, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.tabWidget, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1090, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Losowarka cytatów"))
        self.label_cytat.setText(_translate("MainWindow", "Cytat"))
        self.label_autor.setText(_translate("MainWindow", "Autor   "))
        self.button_previous.setText(_translate("MainWindow", "Previous"))
        self.button_random.setText(_translate("MainWindow", "Random"))
        self.button_next.setText(_translate("MainWindow", "Next"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_losuj), _translate("MainWindow", "Losuj"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
